### ISSUE TITLE
FR: IP addresses

### ISSUE THREAD

**Issue by gerroon** [nextcloud/files_downloadactivity#34] opened 2018-05-20 22:55 UTC
HI

I use this app to track my shares but one thing I am missing is to be able to diifferentiate between anon downloads. It would be nice if we could see the ip addresses of the non NC user downloaders.

thanks

**Comment by nickvergessen** [comment] 2018-12-12 11:47
See my response at #37

**Comment by nickvergessen** [comment] 2018-12-12 11:48
Also duplicate of #30

**Closed by nickvergessen** 2018-12-12 11:47 UTC
