### ISSUE TITLE
Multiple download notifications for public share link

### ISSUE THREAD

**Issue by DesertCookie** [nextcloud/files_downloadactivity#79] opened 2021-08-19 09:19 UTC
### Steps to reproduce

1. Share a file via a public link.
2. Enable notifications about downloads.
3. Have someone download the file.

### Expected behaviour

One notification should be spawned, instead of multiple.

### Actual behaviour

More than a dozen notifications get spawned when someone downloads a shared file.

![downloads](https://user-images.githubusercontent.com/17095983/130041626-5d3037af-39cb-4088-a803-288ce4f3455d.PNG)

### Server configuration

I am using [this Docker container](https://hub.docker.com/r/torkalis/nextcloudsmb/) in Unraid. My NC version is 22.0.0, with the *Activities for shared file downloads, visible to all admins* being of version 1.10.0.

**Failed integrity checks:**

```
- core
	- EXTRA_FILE
		- nextcloud.log

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [nextcloud.log] => Array
                        (
                            [expected] => 
                            [current] => bf7142c5433a39952156ae670e2879aa40b2bdfba7f73b83485f9a147bc93a5ac04c0492ac6cada93609b902e656685f1870fa954cbbcc4e81a1ca1b4b367dc4
                        )

                )

        )

)
```

**Nextcloud configuration:**

```
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'redis' => 
  array (
    'host' => 'REDUCTED',
    'port' => '6379',
    'password' => 'REDUCTED',
  ),
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => 'REDUCTED',
  'passwordsalt' => 'REDUCTED',
  'secret' => 'REDUCTED',
  'trusted_domains' => 
  array (
    0 => 'REDUCTED',
    1 => 'REDUCTED',
    2 => 'REDUCTED',
  ),
  'trusted_proxies' => 
  array (
    0 => 'REDUCTED',
    1 => 'REDUCTED',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '22.0.0.11',
  'overwrite.cli.url' => 'REDUCTEDe',
  'overwriteprotocol' => 'https',
  'dbname' => 'REDUCTED',
  'dbhost' => 'REDUCTED',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'REDUCTED',
  'dbpassword' => 'REDUCTED',
  'installed' => true,
  'app_install_overwrite' => 
  array (
    0 => 'metadata',
    1 => 'twofactor_yubikey',
    2 => 'occweb',
    3 => 'w2g2',
    4 => 'files_lock',
    5 => 'files_readmemd',
    6 => 'talk_matterbridge',
    7 => 'sharerenamer',
    8 => 'whiteboard',
    9 => 'groupfolders',
    10 => 'files_trackdownloads',
    11 => 'files_linkeditor',
    12 => 'camerarawpreviews',
    13 => 'extract',
    14 => 'previewgenerator',
    15 => 'pdfdraw',
    16 => 'twofactor_nextcloud_notification',
    17 => 'nextbackup',
    18 => 'announcementcenter',
    19 => 'end_to_end_encryption',
    20 => 'files_texteditor',
    21 => 'data_request',
    22 => 'unsplash',
    23 => 'tasks',
    24 => 'quota_warning',
    25 => 'ransomware_protection',
    26 => 'sharingpath',
    27 => 'talk_simple_poll',
    28 => 'sharepermissions',
    29 => 'mindmap_app',
    30 => 'files_mindmap',
    31 => 'issuetemplate',
  ),
  'versions_retention_obligation' => 'auto, 365',
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'REDUCTED',
  'mail_domain' => 'gmail.com',
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpport' => '465',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'REDUCTED',
  'mail_smtppassword' => 'REDUCTED',
  'loglevel' => 2,
  'maintenance' => false,
  'auth.bruteforce.protection.enabled' => true,
  'defaultapp' => 'files',
  'log_type' => '2',
  'logfile' => '/var/www/html/nextcloud.log',
  'default_phone_region' => 'DE',
  'theme' => '',
  'allow_local_remote_servers' => true,
  'onlyoffice' => 
  array (
    'verify_peer_off' => true,
  ),
  'preview_max_x' => '2048',
  'preview_max_y' => '2048',
  'jpeg_quality' => '60',
);
```

### Client configuration
Mostly unknown. Probably mostly mobile browsers (Firefox, Chrome).

**Comment by nickvergessen** [comment] 2021-08-19 14:00
Duplicate of https://github.com/nextcloud/files_downloadactivity/issues/47

**Closed by nickvergessen** 2021-08-19 14:00 UTC
